### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by Gerardo34** [shichao-an/soundmeter#11]
When I tried to run a script I made, I got this message: 
cannot execute binary file: Exec format error
I can run the script without any problem directly from the console, but the trigger function always get that error.
I am using raspbian if that helps.

**Comment by shichao-an** [comment]
@Gerardo34 What is the permission of your script? Do you have executable bits on? And do you have a correct shebang in the beginning of the script?

**Comment by Gerardo34** [comment]
Ty, I solved it with the shebang :)
