### ISSUE TITLE
some problem with php

### ISSUE THREAD

**Issue by snoobel** [shichao-an/soundmeter#2]
hello
thank you for this open-software it's really nice 
I Work on Raspberry Pi and his Apache server but i have an issue when i launch soundmeter using a php script, the program runs but i don't have the display of the RMS value, i tried a lot of things; like changing permission, groups ... and nothing works. Do you what could be the issue ?

**Comment by shichao-an** [comment]
Hi @snoobel ,

Can you provide more details?

**Comment by snoobel** [comment]
hi @shichao-an, i work on this issue this morning and i found the problem, with apache and python there is a conflict with the standard output, so the RMS values were not displayed , but with your log option it solved the issue thanks a lot !
